_target_: src.models.ocr_module.OCRLitModule

defaults:
  - _self_
  - net: resnet50_transformers

# pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth # vgg19_transformers
# pretrain: https://vocr.vn/data/vietocr/vgg_seq2seq.pth # vgg19_seq2seq
pretrain: null

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001
  betas: [0.9, 0.98]
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.001
  pct_start: 0.1
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 2667

compile: False

vocab:
  _target_: src.data.components.ocr_vocab.Vocab
  chars: aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ-