_target_: src.models.components.vietocr_net.VietOCR
_partial_: True
backbone: resnet50
cnn_args:
  # pretrained: false
  ss:
    - [2, 2]
    - [2, 1]
    - [2, 1]
    - [2, 1]
    - [1, 1]          
  hidden: 256
seq_modeling: seq2seq
transformer_args:
  encoder_hidden: 256
  decoder_hidden: 256
  img_channel: 256
  decoder_embedded: 256
  dropout: 0.1